//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.17 at 08:49:44 PM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bis.kegoc.kz/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sap.saleInvoiceRev;
