//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.25 at 08:52:59 AM ALMT 
//


package sap.invoiceRev;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sap.invoiceRev package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReversedInvoice_QNAME = new QName("urn:kegoc.kz:BIS:LO_0002_4_ReversedInvoice", "ReversedInvoice");
    private final static QName _Response_QNAME = new QName("urn:kegoc.kz:BIS:CommonObjects", "Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sap.invoiceRev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link ReversedInvoice }
     * 
     */
    public ReversedInvoice createReversedInvoice() {
        return new ReversedInvoice();
    }

    /**
     * Create an instance of {@link ExchangeLogData }
     * 
     */
    public ExchangeLogData createExchangeLogData() {
        return new ExchangeLogData();
    }

    /**
     * Create an instance of {@link ExchangeFaultData }
     * 
     */
    public ExchangeFaultData createExchangeFaultData() {
        return new ExchangeFaultData();
    }

    /**
     * Create an instance of {@link FaultMessage }
     * 
     */
    public FaultMessage createFaultMessage() {
        return new FaultMessage();
    }

    /**
     * Create an instance of {@link Response.Item }
     * 
     */
    public Response.Item createResponseItem() {
        return new Response.Item();
    }

    /**
     * Create an instance of {@link ReversedInvoice.Item }
     * 
     */
    public ReversedInvoice.Item createReversedInvoiceItem() {
        return new ReversedInvoice.Item();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReversedInvoice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:kegoc.kz:BIS:LO_0002_4_ReversedInvoice", name = "ReversedInvoice")
    public JAXBElement<ReversedInvoice> createReversedInvoice(ReversedInvoice value) {
        return new JAXBElement<ReversedInvoice>(_ReversedInvoice_QNAME, ReversedInvoice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:kegoc.kz:BIS:CommonObjects", name = "Response")
    public JAXBElement<Response> createResponse(Response value) {
        return new JAXBElement<Response>(_Response_QNAME, Response.class, null, value);
    }

}
