//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 01:48:47 PM ALMT 
//


package sap.contract.mm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Contract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contract"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="contractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="extContractNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="contractNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="contractDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="purchaseGroup" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="taxCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="vendorNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="consignorNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="currencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *                   &lt;element name="paymentCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="row" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ReqNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="ReqPosNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PozNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="PozText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                             &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                             &lt;element name="MatGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="CostCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="Account" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contract", namespace = "urn:kegoc.kz:BIS:ZMM_0042_Contract", propOrder = {
    "item"
})
public class Contract {

    protected List<Contract.Item> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contract.Item }
     * 
     * 
     */
    public List<Contract.Item> getItem() {
        if (item == null) {
            item = new ArrayList<Contract.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="contractType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="extContractNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="contractNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="contractDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="purchaseGroup" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="taxCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="vendorNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="consignorNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="currencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
     *         &lt;element name="paymentCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="row" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ReqNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="ReqPosNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PozNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="PozText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                   &lt;element name="MatGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="CostCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="Account" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "contractType",
        "extContractNum",
        "contractNum",
        "contractDate",
        "purchaseGroup",
        "taxCode",
        "companyCode",
        "vendorNum",
        "consignorNum",
        "currencyCode",
        "amount",
        "paymentCode",
        "startDate",
        "endDate",
        "row"
    })
    public static class Item {

        protected long id;
        @XmlElement(required = true)
        protected String contractType;
        @XmlElement(required = true)
        protected String extContractNum;
        protected String contractNum;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar contractDate;
        @XmlElement(required = true)
        protected String purchaseGroup;
        @XmlElement(required = true)
        protected String taxCode;
        @XmlElement(required = true)
        protected String companyCode;
        @XmlElement(required = true)
        protected String vendorNum;
        @XmlElement(required = true)
        protected String consignorNum;
        protected String currencyCode;
        protected Double amount;
        @XmlElement(required = true)
        protected String paymentCode;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar startDate;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endDate;
        protected List<Contract.Item.Row> row;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the contractType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractType() {
            return contractType;
        }

        /**
         * Sets the value of the contractType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractType(String value) {
            this.contractType = value;
        }

        /**
         * Gets the value of the extContractNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtContractNum() {
            return extContractNum;
        }

        /**
         * Sets the value of the extContractNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtContractNum(String value) {
            this.extContractNum = value;
        }

        /**
         * Gets the value of the contractNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractNum() {
            return contractNum;
        }

        /**
         * Sets the value of the contractNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractNum(String value) {
            this.contractNum = value;
        }

        /**
         * Gets the value of the contractDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getContractDate() {
            return contractDate;
        }

        /**
         * Sets the value of the contractDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setContractDate(XMLGregorianCalendar value) {
            this.contractDate = value;
        }

        /**
         * Gets the value of the purchaseGroup property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPurchaseGroup() {
            return purchaseGroup;
        }

        /**
         * Sets the value of the purchaseGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPurchaseGroup(String value) {
            this.purchaseGroup = value;
        }

        /**
         * Gets the value of the taxCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxCode() {
            return taxCode;
        }

        /**
         * Sets the value of the taxCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxCode(String value) {
            this.taxCode = value;
        }

        /**
         * Gets the value of the companyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyCode() {
            return companyCode;
        }

        /**
         * Sets the value of the companyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyCode(String value) {
            this.companyCode = value;
        }

        /**
         * Gets the value of the vendorNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVendorNum() {
            return vendorNum;
        }

        /**
         * Sets the value of the vendorNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVendorNum(String value) {
            this.vendorNum = value;
        }

        /**
         * Gets the value of the consignorNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConsignorNum() {
            return consignorNum;
        }

        /**
         * Sets the value of the consignorNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConsignorNum(String value) {
            this.consignorNum = value;
        }

        /**
         * Gets the value of the currencyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyCode() {
            return currencyCode;
        }

        /**
         * Sets the value of the currencyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyCode(String value) {
            this.currencyCode = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setAmount(Double value) {
            this.amount = value;
        }

        /**
         * Gets the value of the paymentCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentCode() {
            return paymentCode;
        }

        /**
         * Sets the value of the paymentCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentCode(String value) {
            this.paymentCode = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Contract.Item.Row }
         * 
         * 
         */
        public List<Contract.Item.Row> getRow() {
            if (row == null) {
                row = new ArrayList<Contract.Item.Row>();
            }
            return this.row;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ReqNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="ReqPosNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PozNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="PozText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *         &lt;element name="MatGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="CostCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="Account" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "reqNum",
            "reqPosNum",
            "pozNum",
            "pozText",
            "unit",
            "quantity",
            "price",
            "matGroup",
            "costCenter",
            "account"
        })
        public static class Row {

            @XmlElement(name = "ReqNum")
            protected String reqNum;
            @XmlElement(name = "ReqPosNum")
            protected String reqPosNum;
            @XmlElement(name = "PozNum", required = true)
            protected String pozNum;
            @XmlElement(name = "PozText", required = true)
            protected String pozText;
            @XmlElement(required = true)
            protected String unit;
            protected double quantity;
            protected double price;
            @XmlElement(name = "MatGroup")
            protected String matGroup;
            @XmlElement(name = "CostCenter")
            protected String costCenter;
            @XmlElement(name = "Account")
            protected String account;

            /**
             * Gets the value of the reqNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReqNum() {
                return reqNum;
            }

            /**
             * Sets the value of the reqNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReqNum(String value) {
                this.reqNum = value;
            }

            /**
             * Gets the value of the reqPosNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReqPosNum() {
                return reqPosNum;
            }

            /**
             * Sets the value of the reqPosNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReqPosNum(String value) {
                this.reqPosNum = value;
            }

            /**
             * Gets the value of the pozNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPozNum() {
                return pozNum;
            }

            /**
             * Sets the value of the pozNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPozNum(String value) {
                this.pozNum = value;
            }

            /**
             * Gets the value of the pozText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPozText() {
                return pozText;
            }

            /**
             * Sets the value of the pozText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPozText(String value) {
                this.pozText = value;
            }

            /**
             * Gets the value of the unit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnit() {
                return unit;
            }

            /**
             * Sets the value of the unit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnit(String value) {
                this.unit = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             */
            public double getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             */
            public void setQuantity(double value) {
                this.quantity = value;
            }

            /**
             * Gets the value of the price property.
             * 
             */
            public double getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             */
            public void setPrice(double value) {
                this.price = value;
            }

            /**
             * Gets the value of the matGroup property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMatGroup() {
                return matGroup;
            }

            /**
             * Sets the value of the matGroup property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMatGroup(String value) {
                this.matGroup = value;
            }

            /**
             * Gets the value of the costCenter property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCostCenter() {
                return costCenter;
            }

            /**
             * Sets the value of the costCenter property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCostCenter(String value) {
                this.costCenter = value;
            }

            /**
             * Gets the value of the account property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccount() {
                return account;
            }

            /**
             * Sets the value of the account property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccount(String value) {
                this.account = value;
            }

        }

    }

}
