//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.21 at 04:08:15 PM ALMT 
//


package sap.contract.mm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Contract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contract"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ContractID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SuperiorContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Supplier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="LegalContractNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ContractDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="PReqNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="PeriodBeginDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="PeriodEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="PaymentTerms" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="PurchasingOrg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="PurchasingGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="TaxCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contract", namespace = "urn:kegoc.kz:BIS:ZMM_0042_Contract", propOrder = {
    "item"
})
public class Contract {

    protected List<Contract.Item> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contract.Item }
     * 
     * 
     */
    public List<Contract.Item> getItem() {
        if (item == null) {
            item = new ArrayList<Contract.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ContractID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SuperiorContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Supplier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ContractType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="LegalContractNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ContractDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="PReqNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="PeriodBeginDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="PeriodEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="PaymentTerms" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="PurchasingOrg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="PurchasingGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="TaxCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contractID",
        "superiorContract",
        "supplier",
        "contractType",
        "legalContractNum",
        "contractDate",
        "pReqNum",
        "periodBeginDate",
        "periodEndDate",
        "paymentTerms",
        "purchasingOrg",
        "purchasingGroup",
        "taxCode"
    })
    public static class Item {

        @XmlElement(name = "ContractID")
        protected String contractID;
        @XmlElement(name = "SuperiorContract")
        protected String superiorContract;
        @XmlElement(name = "Supplier")
        protected String supplier;
        @XmlElement(name = "ContractType")
        protected String contractType;
        @XmlElement(name = "LegalContractNum")
        protected String legalContractNum;
        @XmlElement(name = "ContractDate")
        protected String contractDate;
        @XmlElement(name = "PReqNum")
        protected String pReqNum;
        @XmlElement(name = "PeriodBeginDate")
        protected String periodBeginDate;
        @XmlElement(name = "PeriodEndDate")
        protected String periodEndDate;
        @XmlElement(name = "PaymentTerms")
        protected String paymentTerms;
        @XmlElement(name = "PurchasingOrg")
        protected String purchasingOrg;
        @XmlElement(name = "PurchasingGroup")
        protected String purchasingGroup;
        @XmlElement(name = "TaxCode")
        protected String taxCode;

        /**
         * Gets the value of the contractID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractID() {
            return contractID;
        }

        /**
         * Sets the value of the contractID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractID(String value) {
            this.contractID = value;
        }

        /**
         * Gets the value of the superiorContract property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuperiorContract() {
            return superiorContract;
        }

        /**
         * Sets the value of the superiorContract property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuperiorContract(String value) {
            this.superiorContract = value;
        }

        /**
         * Gets the value of the supplier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupplier() {
            return supplier;
        }

        /**
         * Sets the value of the supplier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupplier(String value) {
            this.supplier = value;
        }

        /**
         * Gets the value of the contractType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractType() {
            return contractType;
        }

        /**
         * Sets the value of the contractType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractType(String value) {
            this.contractType = value;
        }

        /**
         * Gets the value of the legalContractNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLegalContractNum() {
            return legalContractNum;
        }

        /**
         * Sets the value of the legalContractNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLegalContractNum(String value) {
            this.legalContractNum = value;
        }

        /**
         * Gets the value of the contractDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractDate() {
            return contractDate;
        }

        /**
         * Sets the value of the contractDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractDate(String value) {
            this.contractDate = value;
        }

        /**
         * Gets the value of the pReqNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPReqNum() {
            return pReqNum;
        }

        /**
         * Sets the value of the pReqNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPReqNum(String value) {
            this.pReqNum = value;
        }

        /**
         * Gets the value of the periodBeginDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPeriodBeginDate() {
            return periodBeginDate;
        }

        /**
         * Sets the value of the periodBeginDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPeriodBeginDate(String value) {
            this.periodBeginDate = value;
        }

        /**
         * Gets the value of the periodEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPeriodEndDate() {
            return periodEndDate;
        }

        /**
         * Sets the value of the periodEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPeriodEndDate(String value) {
            this.periodEndDate = value;
        }

        /**
         * Gets the value of the paymentTerms property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentTerms() {
            return paymentTerms;
        }

        /**
         * Sets the value of the paymentTerms property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentTerms(String value) {
            this.paymentTerms = value;
        }

        /**
         * Gets the value of the purchasingOrg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPurchasingOrg() {
            return purchasingOrg;
        }

        /**
         * Sets the value of the purchasingOrg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPurchasingOrg(String value) {
            this.purchasingOrg = value;
        }

        /**
         * Gets the value of the purchasingGroup property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPurchasingGroup() {
            return purchasingGroup;
        }

        /**
         * Sets the value of the purchasingGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPurchasingGroup(String value) {
            this.purchasingGroup = value;
        }

        /**
         * Gets the value of the taxCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxCode() {
            return taxCode;
        }

        /**
         * Sets the value of the taxCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxCode(String value) {
            this.taxCode = value;
        }

    }

}
