//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.09 at 03:31:34 PM ALMT 
//


package sap.saleInvoice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EstimatedChargeInvoices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstimatedChargeInvoices"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="docType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="srcDocNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="orderNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="turnoverDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="accountingDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="customerNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="consigneeNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="contractNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="extContractNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *                   &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *                   &lt;element name="currencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="row" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="posNum" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                             &lt;element name="posName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="itemNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                             &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                             &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                             &lt;element name="taxRate" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstimatedChargeInvoices", namespace = "urn:kegoc.kz:BIS:LO_0002_1_EstimatedChargeInvoice", propOrder = {
    "item"
})
public class EstimatedChargeInvoices {

    protected List<EstimatedChargeInvoices.Item> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstimatedChargeInvoices.Item }
     * 
     * 
     */
    public List<EstimatedChargeInvoices.Item> getItem() {
        if (item == null) {
            item = new ArrayList<EstimatedChargeInvoices.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="docType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="srcDocNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="orderNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="turnoverDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="accountingDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="customerNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="consigneeNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="contractNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="extContractNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
     *         &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
     *         &lt;element name="currencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="row" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="posNum" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *                   &lt;element name="posName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="itemNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                   &lt;element name="taxRate" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "docType",
        "srcDocNum",
        "orderNum",
        "turnoverDate",
        "accountingDate",
        "customerNum",
        "consigneeNum",
        "contractNum",
        "extContractNum",
        "companyCode",
        "amount",
        "tax",
        "currencyCode",
        "row"
    })
    public static class Item {

        protected long id;
        @XmlElement(required = true)
        protected String docType;
        protected String srcDocNum;
        protected String orderNum;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar turnoverDate;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar accountingDate;
        @XmlElement(required = true)
        protected String customerNum;
        @XmlElement(required = true)
        protected String consigneeNum;
        @XmlElement(required = true)
        protected String contractNum;
        protected String extContractNum;
        @XmlElement(required = true)
        protected String companyCode;
        protected Double amount;
        protected Double tax;
        protected String currencyCode;
        protected List<EstimatedChargeInvoices.Item.Row> row;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the docType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocType() {
            return docType;
        }

        /**
         * Sets the value of the docType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocType(String value) {
            this.docType = value;
        }

        /**
         * Gets the value of the srcDocNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrcDocNum() {
            return srcDocNum;
        }

        /**
         * Sets the value of the srcDocNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrcDocNum(String value) {
            this.srcDocNum = value;
        }

        /**
         * Gets the value of the orderNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderNum() {
            return orderNum;
        }

        /**
         * Sets the value of the orderNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderNum(String value) {
            this.orderNum = value;
        }

        /**
         * Gets the value of the turnoverDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTurnoverDate() {
            return turnoverDate;
        }

        /**
         * Sets the value of the turnoverDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTurnoverDate(XMLGregorianCalendar value) {
            this.turnoverDate = value;
        }

        /**
         * Gets the value of the accountingDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getAccountingDate() {
            return accountingDate;
        }

        /**
         * Sets the value of the accountingDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setAccountingDate(XMLGregorianCalendar value) {
            this.accountingDate = value;
        }

        /**
         * Gets the value of the customerNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerNum() {
            return customerNum;
        }

        /**
         * Sets the value of the customerNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerNum(String value) {
            this.customerNum = value;
        }

        /**
         * Gets the value of the consigneeNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConsigneeNum() {
            return consigneeNum;
        }

        /**
         * Sets the value of the consigneeNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConsigneeNum(String value) {
            this.consigneeNum = value;
        }

        /**
         * Gets the value of the contractNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractNum() {
            return contractNum;
        }

        /**
         * Sets the value of the contractNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractNum(String value) {
            this.contractNum = value;
        }

        /**
         * Gets the value of the extContractNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtContractNum() {
            return extContractNum;
        }

        /**
         * Sets the value of the extContractNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtContractNum(String value) {
            this.extContractNum = value;
        }

        /**
         * Gets the value of the companyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyCode() {
            return companyCode;
        }

        /**
         * Sets the value of the companyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyCode(String value) {
            this.companyCode = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setAmount(Double value) {
            this.amount = value;
        }

        /**
         * Gets the value of the tax property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getTax() {
            return tax;
        }

        /**
         * Sets the value of the tax property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setTax(Double value) {
            this.tax = value;
        }

        /**
         * Gets the value of the currencyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyCode() {
            return currencyCode;
        }

        /**
         * Sets the value of the currencyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyCode(String value) {
            this.currencyCode = value;
        }

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EstimatedChargeInvoices.Item.Row }
         * 
         * 
         */
        public List<EstimatedChargeInvoices.Item.Row> getRow() {
            if (row == null) {
                row = new ArrayList<EstimatedChargeInvoices.Item.Row>();
            }
            return this.row;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="posNum" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
         *         &lt;element name="posName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="itemNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *         &lt;element name="taxRate" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "posNum",
            "posName",
            "itemNum",
            "unit",
            "quantity",
            "price",
            "amount",
            "taxRate"
        })
        public static class Row {

            protected long posNum;
            @XmlElement(required = true)
            protected String posName;
            @XmlElement(required = true)
            protected String itemNum;
            @XmlElement(required = true)
            protected String unit;
            protected double quantity;
            protected double price;
            protected double amount;
            protected double taxRate;

            /**
             * Gets the value of the posNum property.
             * 
             */
            public long getPosNum() {
                return posNum;
            }

            /**
             * Sets the value of the posNum property.
             * 
             */
            public void setPosNum(long value) {
                this.posNum = value;
            }

            /**
             * Gets the value of the posName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPosName() {
                return posName;
            }

            /**
             * Sets the value of the posName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPosName(String value) {
                this.posName = value;
            }

            /**
             * Gets the value of the itemNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getItemNum() {
                return itemNum;
            }

            /**
             * Sets the value of the itemNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setItemNum(String value) {
                this.itemNum = value;
            }

            /**
             * Gets the value of the unit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnit() {
                return unit;
            }

            /**
             * Sets the value of the unit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnit(String value) {
                this.unit = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             */
            public double getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             */
            public void setQuantity(double value) {
                this.quantity = value;
            }

            /**
             * Gets the value of the price property.
             * 
             */
            public double getPrice() {
                return price;
            }

            /**
             * Sets the value of the price property.
             * 
             */
            public void setPrice(double value) {
                this.price = value;
            }

            /**
             * Gets the value of the amount property.
             * 
             */
            public double getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             */
            public void setAmount(double value) {
                this.amount = value;
            }

            /**
             * Gets the value of the taxRate property.
             * 
             */
            public double getTaxRate() {
                return taxRate;
            }

            /**
             * Sets the value of the taxRate property.
             * 
             */
            public void setTaxRate(double value) {
                this.taxRate = value;
            }

        }

    }

}
