//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.23 at 01:44:24 PM ALMT 
//


package sap.saleInvoice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sap.saleInvoice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateInvoices_QNAME = new QName("http://bis.kegoc.kz/soap", "createInvoices");
    private final static QName _CreateInvoicesResponse_QNAME = new QName("http://bis.kegoc.kz/soap", "createInvoicesResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sap.saleInvoice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateInvoices }
     * 
     */
    public CreateInvoices createCreateInvoices() {
        return new CreateInvoices();
    }

    /**
     * Create an instance of {@link CreateInvoicesResponse }
     * 
     */
    public CreateInvoicesResponse createCreateInvoicesResponse() {
        return new CreateInvoicesResponse();
    }

    /**
     * Create an instance of {@link SaleInvoice }
     * 
     */
    public SaleInvoice createSaleInvoice() {
        return new SaleInvoice();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link Msg }
     * 
     */
    public Msg createMsg() {
        return new Msg();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateInvoices }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bis.kegoc.kz/soap", name = "createInvoices")
    public JAXBElement<CreateInvoices> createCreateInvoices(CreateInvoices value) {
        return new JAXBElement<CreateInvoices>(_CreateInvoices_QNAME, CreateInvoices.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateInvoicesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bis.kegoc.kz/soap", name = "createInvoicesResponse")
    public JAXBElement<CreateInvoicesResponse> createCreateInvoicesResponse(CreateInvoicesResponse value) {
        return new JAXBElement<CreateInvoicesResponse>(_CreateInvoicesResponse_QNAME, CreateInvoicesResponse.class, null, value);
    }

}
